### ISSUE TITLE
Laravel 5.6 - Error during composer install

### ISSUE THREAD

**Issue by 06chaynes** [swisnl/laravel-graylog2#12]
I get an error when trying to install the package on a fresh Laravel 5.6 install. 

The error is: `Call to undefined method Monolog\Logger::getMonolog()`

**Comment by bbrala** [comment]
Hmm, it seems the version contraint is wrong. There is no support for 5.6 yet, there are some changes in how logging works which we haven't implemented yet, sorry.

**Comment by 06chaynes** [comment]
Not a problem, thanks for the quick response. Are these changes on the roadmap to be added by chance?

**Comment by bbrala** [comment]
We know of the issue, it does seem it will need to work quite differently. Also we won't be running 5.6 in out projects before this oktober, which means we have no real usage for that case at the moment.

We should get to it, but it might take a bit sorry.

**Comment by 06chaynes** [comment]
Totally understandable, thanks again!

**Comment by barryvanveen** [comment]
We have decided to discontinue further development of this package since we switched our logging services from Graylog to Bugsnag. This means we won't be updating this package to make it compatible with Laravel 5.6 and up.

If anyone is interested in maintaining and updating this package, please let us know.

**Comment by 06chaynes** [comment]
Bugsnag looks enticing, I'll check it out. Thanks for the heads up!
